linux-notification-center.cabal

Otherwise, TH breaks if one tries to build this using `cabal new-install` (either from repo or from cabal's sdist tarball)

Add extra files used in TH to cabalfile

---

src/NotificationCenter/Notifications.hs

Currently, embedding `<img .../>` tags is not supported.
Fixes #27.

Remove `body-images` from capabilities

---

Makefile

Before, there would be a folder made with the name "{de,en}".

Fix make file install-lang

---

README.org
src/Config.hs
src/NotificationCenter/Notifications.hs
src/NotificationCenter/Notifications/Data.hs
src/NotificationCenter/Notifications/NotificationPopup.hs

closes #47 
Ideally, those options, `distanceRight` and `distanceTop` would be all customizable with a percentage as well instead of only a X/Y anchor; that is out of scope for this MR, though.

Allow customization of Top and Right displacement per notification

---

stack.yaml

Hi.
In order to save other Nix users the hassle of figuring out the packages they have to install in order to build the project with the `stack` tool, this PR adds the required packages to the `nix` section.
`stack` will take care of providing the required dependencies in ghc's build environment on NixOS automatically.

stack: Add `nix` section with required packages

---

src/NotificationCenter/Notifications/NotificationPopup.hs

Problem: button clicks which aren't bound in a configuration file to either
dismiss or perform an action on a notification crash the notification center
Solution: add a catch-all clause to mouse button handling routine, closing
the notification if an unknown button press is received.
Closes https://github.com/phuhl/linux_notification_center/issues/101

Handle unbound mouse button clicks on a notification

---

stack.yaml

Could not compile with gi-pango-1.0.22 as specified in the latest stack.yaml file.
This is due to a bug in that specific version where it could not parse harfbuzz.
Further information on the error as well as the merge to fix it in here:
https://github.com/haskell-gi/haskell-gi/issues/298
The fix has been implemented in gi-pango-1.0.23. That package also requires gi-harfbuzz-0.0.3 as a new dependency. 
The rest of the dependencies have been updated in accordance with this sheet:
https://hackage.haskell.org/package/gi-pango
I was able to build successfully using this configuration.
Definitely closes #85 , could potentially close #45 as well since it was a gtk3 error and gi-gtk is bumped to 3.0.36. There is a thread mentioning it was fixed in gtk3-3.24.7
https://bugs.archlinux.org/task/61486

Update Gi-pango and Related Dependencies

---

src/Helpers.hs

Closes #107 
The change was more trivial than i thought. If i viewed all the hs filed correctly, this is the only file that imports this specific function.
Deprecation listed here:
http://hackage.haskell.org/package/mtl-2.2.2/docs/Control-Monad-Error.html

Replace Depricated Control.Monad.Error with Control.Monad.Except

---

linux-notification-center.cabal
src/NotificationCenter.hs
src/NotificationCenter/Notifications.hs
stack.yaml
stack.yaml.lock

I am unsure why the upper bound was set to `<1` for `dbus`. The changes to support 1.x were rather trivial and nothing has seemingly broken from what I can tell. I left support for the older versions of the library in case it is important. I am fine with removing older support if that is wanted.
The switch to env-locale from system-locale is my main motivation. As mentioned in the commit, system-locale requires the command `locale` visible in PATH. This is not always the case. See issue #63 for an example.

Support 1.x versions of the D-Bus client library and switch to env-locale

---

linux-notification-center.cabal
src/NotificationCenter/Notifications.hs

getDesktopFile now looks in the following places:
- $XDG_DATA_HOME/applications
\ $HOME/.local/share/applications (if XDG_DATA_HOME is unset)
- /usr/local/share/applications
- /usr/share/applications
- $XDG_DATA_DIRS/applications (enumerates through if multiple)
The first match is desktop file which shall be used according to spec.
This commit also correct the issue of readFile not expanding the tilde.
Resolves #122.

Notifications.hs: respect the XDG specification

---

src/Helpers.hs

Forgot to concatenate the Makefile paths to the paths from cabal.
Should fix #184, @xircon can you try to see if this fixes your problem?

src/Helpers.hs: search locales in Makefile paths

---

src/NotificationCenter.hs
src/NotificationCenter/Button.hs
src/NotificationCenter/Notifications/Action.hs

Use `interruptProcessGroupOf` to ensure the shell is killed.
Alternatively, if not using `shell` (which is used internally by
spawnCommand) terminateProcess would work.
This fixes #126, @ahmubashshir if you want to give this a test.

remove deprecated runCommand and banish zombies

---

src/Helpers.hs
src/NotificationCenter.hs

Fixes https://github.com/phuhl/linux_notification_center/issues/184, and fixes https://github.com/phuhl/linux_notification_center/issues/188.
Hopefully this should cover everything.
Specifically this addresses:
- When LANG is set to a locale that there is no translation for.
- Falls back to English.
- When translations are missing entirely.
- Fail with grace.
In addition I ran into removeOuterLetters throwing an exception when I was using it in adding another feature. Small change to handle the exception.

Localization fixes and an "improvement" to the removeOuterLetters function

---

src/NotificationCenter/Notifications/NotificationPopup.hs
stack.yaml
stack.yaml.lock

Stack lts-19.4 has their `haskell-gi` packages figured out so they no longer need to be pin in `extra-deps` as well as `ConfigFile`, `MissingH` and `random` are now provided once again by the resolver.

Support GHC 9.0.2 / stack lts-19.4

---

deadd-notification-center.cabal
stack.yaml

I know pretty much nothing about Haskall other than its package management being really annoying, so I don't expect this to get merged. But this is what I needed to change to get this to compile on Fedora 36. Might help others.

fix: gi-pango version for compilation to work

---

Makefile

This broke the deadd-notification-center-bin PKGBUILD in the AUR

Add missing ${DESTDIR} to CSS_CONFIG_DIR

---

src/NotificationCenter.hs

Currently, there is a regression where `deadd.css` is only read from `/etc/xdg/deadd/deadd.css`, this returns the fallback to `$XDG_CONFIG_HOME/deadd/deadd.css`.

src/NotificationCenter.hs: read deadd.css from /etc and XDG config

---

stack.yaml
stack.yaml.lock

Bummp the Stack LTS resolver to 21.3, and remove extra-deps that are now part of the LTS snapshot.
This fixed the build for me, but considering it's been broken before, I wonder what might be missing for it to be completely reproducible. In another PR I hope to pin more package versions.

stack: bump stack resolver to lts 21.3

---

.github/workflows/main.yml

This PR makes the following improvements to the CI workflow:
- The latest stable version of Stack is used instead of a fixed version. This
shouldn't be a problem, as the Stack configuration dictates what version of
GHC and which packages are downloaded.
- No version of GHC is fixed through the CI workflow, and instead we rely on
what is written on `stack.yaml`, as originally intended, thus using whatever
version our chosen resolver points to.
- The checkout action is always executed when the workflow runs, as it is
imperative for the rest of the workflow to work.
- The global Stack directory is cached before Stack and GHC are setup, ensuring
we don't waste Actions minutes downloading the same GHC installation over and
over.
- The Stack work directory, containing built dependencies and …

ci: use latest stack, resolver ghc, and cache deps

---

README.org
src/Config.hs
src/NotificationCenter/Notifications/AbstractNotification.hs

This pull request adds a configuration option that allows the notification body in popup windows to be hidden (set to invisible) if it is empty.
This is especially useful for transient notifications that do not need a body, but display a progress bar or buttons (e.g. volume control).

feat: hide body in popup if empty
